blank_issues_enabled: false
contact_links:
  - name: 🙋 Questions
    url: https://github.com/myeongju-kim/boilerplate-starter/discussions
    about: Please ask questions in Discussions instead of creating an issue.
