name: "✨ Feature Request"
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: textarea
    id: goal
    attributes:
      label: Goal
      description: What problem does this feature solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed Solution
      placeholder: Describe how you would like this feature to work.
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      placeholder: Describe any alternative solutions you’ve considered.
  - type: checkboxes
    id: scope
    attributes:
      label: Scope
      options:
        - label: UI changes required
        - label: API/schema changes required
